package org.traducao.projeto.legenda.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * PROPÓSITO DE NEGÓCIO: prova que o carimbo conta o que o KRONOS fez SEM alterar a legenda que
 * o player exibe, e sem crescer a cada execução.
 *
 * <h2>O prejuízo que originou</h2>
 * Cinco conclusões erradas na auditoria de 07/08/2026 vieram de recalcular por fora o que o
 * pipeline decidiu por dentro — 18.431 falas dadas como resíduo de tradução (eram letra de
 * música achatada), 2.898 dadas como perdidas (eram karaokê descartado de propósito), 364
 * "defeitos" no Unicorn (eram estilos que o {@code application.yml} manda ignorar). O dado
 * existia; o que faltava era o arquivo declarar.
 */
class CarimboCabecalhoLegendaTest {

    private static final String CABECALHO = """
        [Script Info]
        ScriptType: v4.00+
        WrapStyle: 0

        [V4+ Styles]
        Format: Name, Fontname
        Style: Default,Arial
        """;

    /**
     * PROPÓSITO DE NEGÓCIO: o carimbo entra logo após {@code [Script Info]}, prefixado como
     * comentário, com o conteúdo que foi pedido.
     */
    @Test
    @DisplayName("carimba dentro de [Script Info], como comentario")
    void carimbaDentroDoScriptInfo() {
        String saida = CarimboCabecalhoLegenda.aplicar(CABECALHO,
            List.of("traduziu: 404 fala(s) na origem", "lore: Break Blade (break_blade_1)"));

        String[] linhas = saida.split("\n");
        assertEquals("[Script Info]", linhas[0].trim());
        assertEquals("; KRONOS traduziu: 404 fala(s) na origem", linhas[1].trim(),
            "o carimbo tem de vir na PRIMEIRA linha apos [Script Info]");
        assertEquals("; KRONOS lore: Break Blade (break_blade_1)", linhas[2].trim());
        assertTrue(saida.contains("ScriptType: v4.00+"), "o cabecalho original tem de sobreviver");
        assertTrue(saida.contains("Style: Default,Arial"));
    }

    /**
     * PROPÓSITO DE NEGÓCIO: o invariante que impede o cabeçalho de crescer sem limite — e que
     * impede um carimbo velho, com números de OUTRA execução, de continuar no arquivo.
     */
    @Test
    @DisplayName("idempotente: carimbar duas vezes substitui, nao empilha")
    void carimbarDuasVezesSubstitui() {
        String uma = CarimboCabecalhoLegenda.aplicar(CABECALHO, List.of("traduziu: 100 fala(s)"));
        String duas = CarimboCabecalhoLegenda.aplicar(uma, List.of("traduziu: 250 fala(s)"));

        assertEquals(1, contar(duas, "; KRONOS "),
            "duas execucoes deixaram DOIS carimbos: o cabecalho cresce a cada rodada e o numero "
                + "antigo, ja falso, continua no arquivo. Veio:\n" + duas);
        assertTrue(duas.contains("250 fala(s)"), "o carimbo novo tem de estar la");
        assertFalse(duas.contains("100 fala(s)"), "o carimbo VELHO tem de sair");
    }

    /**
     * PROPÓSITO DE NEGÓCIO: comentário que não é nosso não pode ser apagado. O operador e o
     * Aegisub também escrevem linhas com {@code ;} no cabeçalho.
     */
    @Test
    @DisplayName("comentario de terceiro sobrevive ao recarimbo")
    void comentarioDeTerceiroSobrevive() {
        String comAlheio = "[Script Info]\n; Script generated by Aegisub 3.2.2\nScriptType: v4.00+\n";
        String uma = CarimboCabecalhoLegenda.aplicar(comAlheio, List.of("traduziu: 10 fala(s)"));
        String duas = CarimboCabecalhoLegenda.aplicar(uma, List.of("traduziu: 20 fala(s)"));

        assertTrue(duas.contains("; Script generated by Aegisub 3.2.2"),
            "a remocao do carimbo anterior apagou comentario que nao e do KRONOS. Veio:\n" + duas);
    }

    /**
     * PROPÓSITO DE NEGÓCIO: trocar o final de linha de um {@code .ass} no meio do acervo é
     * mudança silenciosa que nenhum teste de conteúdo pegaria.
     */
    @Test
    @DisplayName("preserva a quebra de linha do arquivo")
    void preservaQuebraDeLinha() {
        String crlf = "[Script Info]\r\nScriptType: v4.00+\r\n";
        String saida = CarimboCabecalhoLegenda.aplicar(crlf, List.of("traduziu: 5 fala(s)"));
        assertTrue(saida.contains("; KRONOS traduziu: 5 fala(s)\r\n"),
            "arquivo CRLF recebeu carimbo com LF. Veio:\n" + saida.replace("\r", "<CR>"));
    }

    /**
     * PROPÓSITO DE NEGÓCIO: o carimbo NÃO pode virar diálogo. Se uma linha de carimbo fosse
     * lida como evento, o player mostraria texto do KRONOS por cima do vídeo.
     */
    @Test
    @DisplayName("nenhuma linha de carimbo e Dialogue")
    void carimboNaoViraDialogo() {
        String saida = CarimboCabecalhoLegenda.aplicar(CABECALHO,
            List.of("traduziu: 404 fala(s)", "pendentes: 1 fala(s)"));
        for (String linha : saida.split("\n")) {
            assertFalse(linha.trim().startsWith("Dialogue:"),
                "linha de carimbo virou evento e apareceria no video: " + linha);
        }
    }

    /**
     * PROPÓSITO DE NEGÓCIO: entrada degenerada não pode quebrar a gravação da legenda — o
     * carimbo é acessório e jamais pode custar o arquivo.
     */
    @Test
    @DisplayName("nulo, vazio e cabecalho sem [Script Info] nao quebram")
    void entradaDegeneradaNaoQuebra() {
        assertEquals("", CarimboCabecalhoLegenda.aplicar(null, List.of()));
        assertEquals(CABECALHO, CarimboCabecalhoLegenda.aplicar(CABECALHO, List.of()));
        assertEquals(CABECALHO, CarimboCabecalhoLegenda.aplicar(CABECALHO, null));

        String semSecao = "ScriptType: v4.00+\n";
        String saida = CarimboCabecalhoLegenda.aplicar(semSecao, List.of("traduziu: 1 fala(s)"));
        assertTrue(saida.startsWith("; KRONOS traduziu:"),
            "sem [Script Info] o carimbo vai para o inicio; veio: " + saida);
        assertTrue(saida.contains("ScriptType: v4.00+"));
    }

    private static int contar(String texto, String agulha) {
        int n = 0;
        int i = texto.indexOf(agulha);
        while (i >= 0) {
            n++;
            i = texto.indexOf(agulha, i + agulha.length());
        }
        return n;
    }
}
